VIA_ENABLE = yes
VIAL_ENABLE = yes
OLED_ENABLE = no
ENCODER_ENABLE = yes
CONSOLE_ENABLE = no
EXTRAKEY_ENABLE = yes
ENCODER_MAP_ENABLE = yes
LTO_ENABLE = yes
QMK_SETTINGS = no
MOUSEKEY_ENABLE = yes
COMBO_ENABLE = no
KEY_OVERRIDE_ENABLE = no
CAPS_WORD_ENABLE = no
LAYER_LOCK_ENABLE = no
REPEAT_KEY_ENABLE = no

RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes

#CONVERT_TO = elite_pi
